import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={{ padding: "1rem", backgroundColor: "#f0f0f0", justifyContent: "center", alignItems: "center", borderBottom: "1px solid #ccc", display: "flex", justifyContent: "space-between", alignItems: "center", fontFamily: "var(--font-geist-sans)", color: "inherit", fontSize: "1rem" }}>
          <ul style={{ display: "flex", justifyContent: "center", alignItems: "center", listStyle: "none", margin: 0, padding:10,textAlign: "center", fontFamily: "var(--font-geist-sans)", color: "inherit", fontSize: "1rem" }}>
            <li style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>
              <a href="/" style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>Home</a>
            </li>
            <li style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>
              <a href="/resume_scanning" style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>Resume Scanning</a>
            </li>
            <li style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>
              <a href="/generate_questions" style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>Generate Questions</a>
            </li >
            <li style={{ marginRight: "1rem", fontSize: "1.2rem", fontWeight: "bold", textDecoration: "none", color: "inherit" }}>
              <a href="/pose_analysis" style={{ textDecoration: "none" }}>Pose Analysis</a>
            </li>


            

          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
